webproject/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from webapp import views
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views

urlpatterns = [


    url(r'^reset/$',
    auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt'
    ),
    name='password_reset'),
    url(r'^reset/done/$',
    auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
    name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
    name='password_reset_confirm'),
    url(r'^reset/complete/$',
    auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    name='password_reset_complete'),

    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'),
    name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
    name='password_change_done'),


    url('admin/', admin.site.urls),
    url(r'^signup/$',accounts_views.signup,name ='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    #url(r'^home/$',views.home,name ='home'),
    url(r'^$', views.BoardListView.as_view(), name='home'),
   # url(r'^boards/(?P<pk>\d+)/$',views.boards_topics,name = 'boards_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$',views.new_topics,name = 'new_topics'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='edit_post'),
    url(r'^boards/(?P<pk>\d+)/$', views.TopicListView.as_view(), name='boards_topics'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    url(r'^settings/account/$', accounts_views.UserUpdateView.as_view(), name='my_account'),


    url(r'^api/vi/',include('webapp.api_url'))
    ]
    

webapp/models.py
from django.db import models
import math
from django.contrib.auth.models import User
from datetime import datetime
from django.utils.text import Truncator
from django.db.models import Count
from django.utils.html import mark_safe
from markdown import markdown
# user :The User model is already defined inside a built-in app named auth, 
#which is listed in our INSTALLED_APPS 
#configuration under the namespace django.contrib.auth.
#----------------------------------------------
#what is models?
#The models are basically a representation of your application’s database layout.
#--------------------------------------------------
#All models(Board,Topic,Post) are subclass of the (django.db.models.Model class).
#Each class will be transformed into (database tables).
#-----------------------------------------------------
class Board(models.Model):
	name = models.CharField(max_length=200,unique=True)# unique=True:this parameter not allowed duplicate names
	description = models.CharField(max_length=4000)
	def __str__(self):
		return self.name

	def get_posts_count(self):
		return Post.objects.filter(topic__board=self).count()

	def get_last_post(self):
		return Post.objects.filter(topic__board=self).order_by('-create_at').first()
#Each (field) is represented by instances of (django.db.models.Field) 
#subclasses (built-in Django core) and will be translated into database columns.
#The fields CharField, DateTimeField, etc., are all subclasses of django.db.models.Field and 
#they come included in the Django core – ready to be used.

class Topic(models.Model):
	subject = models.CharField(max_length= 1000)
	last_update = models.DateTimeField(auto_now_add=True)
#this will instruct Django to set the current date and time (auto_now_add=True).
	board = models.ForeignKey(Board,related_name='topics',on_delete=models.CASCADE)
#To create a relationship between the models(Board to Topic to post) is by using the (ForeignKey field).
	starter = models.ForeignKey(User,related_name='topics',on_delete=models.CASCADE)
	views = models.PositiveIntegerField(default=0)
	def __str__(self):
		return self.subject
	def get_page_count(self):
		count = self.posts.count()
		pages = count / 20
		return math.ceil(pages)

	def has_many_pages(self, count=None):
		if count is None:
			count = self.get_page_count()
		return count > 6

	def get_page_range(self):
		count = self.get_page_count()
		if self.has_many_pages(count):
			return range(1, 5)
		return range(1, count + 1)
	def get_last_ten_posts(self):
		return self.posts.order_by('-created_at')[:10]
#Django automatically creates this reverse relationship – the(related_name) is optional. 
#But if we don’t set a name for it, Django will generate it with the name: (class_name)_set,for exanple(Board_set)
class Post(models.Model):
	message = models.TextField(max_length=4000)
	topic = models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
	create_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(null=True)
	created_by = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
	updated_by = models.ForeignKey(User,null=True,related_name='+',on_delete=models.CASCADE)
	def __str__(self):
		truncated_message = Truncator(self.message)
		return truncated_message.chars(30)

	def get_message_as_markdown(self):
		return mark_safe(markdown(self.message, safe_mode='escape'))
#the (related_name='+').This instructs Django that we don’t need this reverse relationship, 
#so it will ignore it.

#(after makemigaratios Django created a file named 0001_initial.py inside the boards/migrations directory.
#It represents the current state of our application’s models. In the next step, 
#Django will use this file to create the tables and columns.)

webapp/forms.py
from django import forms
from .models import Board,Topic,Post

class NewTopicForm(forms.ModelForm):
	message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )

	class Meta:
		model = Topic
		fields = ['subject','message']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']


# Here we added a new field that is message
# associated with Topic model,in meta class.

webapp/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
#from django.http import Http404
from .models import Board,Topic,Post
from .forms import NewTopicForm,PostForm
from django.db.models import Count
from django.views.generic import UpdateView
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from rest_framework import viewsets
from webapp.serilaizer import EmployeeSerializer 

class EmployeeViewset(viewsets.ModelViewSet):
    queryset = Board.objects.all()
    serilaizer_class = EmployeeSerializer


class BoardListView(ListView):
    model = Board
    context_object_name = 'boards'
    template_name = 'webapp/home.html'
#def home(request):
	#H_boards=Board.objects.all()
	#return render(request,'webapp/home.html',{"H_boards":H_boards})

class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'webapp/topics.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        queryset = self.board.topics.order_by('-last_update').annotate(replies=Count('posts') - 1)
        return queryset

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'webapp/topic_posts.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        session_key = 'viewd_topic_{}'.format(self.topic.pk)
        if not self.request.session.get(session_key,False):
            self.topic.views += 1
            self.topic.save()
            self.request.session[session_key]=True
        kwargs['topic'] = self.topic
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.topic = get_object_or_404(Topic, board__pk=self.kwargs.get('pk'), pk=self.kwargs.get('topic_pk'))
        queryset = self.topic.posts.order_by('created_at')
        return queryset

#def boards_topics(request,pk):
	# we are importing 'get_object_or_404'
	#T_boards = get_object_or_404(Board,pk=pk)
	#queryset = T_boards.topics.order_by('-last_update').annotate(replies=Count('posts') - 1)
	#page =request.GET.get('page',1)
	#paginator = Paginator(queryset, 20)
	#try:
		#topics = paginator.page(page)
	#except PageNotAnInteger:
		#topics = paginator.page(1)
	#except EmptyPage:
		#topics = paginator.page(paginator.num_pages)
	#return render(request,'webapp/topics.html',{"T_boards":T_boards,"topics":topics})

	# we can write code like this also
	#try:
	#	boards = Board.objects.get(pk=pk)
	#except Board.DoesNotExist:
	#	raise Http404 
	#return render(request,'webapp/topics.html',{"boards":boards})
#def new_topics(request,pk):
#	N_boards = get_object_or_404(Board, pk=pk)
#	if request.method == 'POST' :

#		subject= request.POST['subject']
#		message = request.POST['message']
#		user1= User.objects.first()

#		topic1= Topic.objects.create(
 #           subject=subject,
  #          board=N_boards,
   #         starter=user1
    #    )
		#post = Post.objects.create(
         #   message=message,
          #  topic=topic1,
           # created_by=user1
        #)
		#return redirect('boards_topics', pk=N_boards.pk)
	#return render(request,'webapp/new_topic.html',{"N_boards":N_boards})

@login_required
def new_topics(request,pk):
	N_boards = get_object_or_404(Board,pk=pk)
	user1 = User.objects.first()
	if request.method == 'POST':
		form = NewTopicForm(request.POST)#just imagine its a html form 
         #in side NewTopicForm class we used Topic model through Meta class reference 
		if form.is_valid():
			topic = form.save(commit=False)# Topic Model 
			topic.board = N_boards 
			#topic.board = N_boards;'board' is from Topic Model 
			topic.starter=request.user # here we are requesting present new topic created user
            # if we used like this topic.starter = user1 we get admin user name.
			topic.save()

			post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=request.user
            )
			return redirect('boards_topics',pk=N_boards.pk)
			return redirect('topic_posts', pk=pk, topic_pk=topic.pk)   # TODO: redirect to the created topic page
	else :
		form = NewTopicForm()
	return render(request,'webapp/new_topic.html',{"N_boards":N_boards,"form":form})

def topic_posts(request, pk,topic_pk):
    topic =get_object_or_404(Topic,board__pk = pk,pk=topic_pk)
    topic.views += 1
    topic.save()
    return render(request, 'webapp/topic_posts.html', {'topic': topic})
 	

@login_required
def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()

            topic.last_update = timezone.now()
            topic.save()
            return redirect('topic_posts', pk=pk, topic_pk=topic_pk)
    else:
        form = PostForm()
    return render(request, 'webapp/reply_topic.html', {'topic': topic, 'form': form})


@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    fields = ('message', )
    template_name = 'webapp/edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)


    def form_valid(self, form):
        post = form.save(commit=False) 
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()
        return redirect('topic_posts', pk=post.topic.board.pk, topic_pk=post.topic.pk)

templates/webapp/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
<head>
	<title>{%block title%}Dango_Boards{%endblock%}</title>
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{%static 'css/web.css'%}">
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
	{%block stylesheet%}{%endblock%}

</head>
<!--This is Master Template Page<-->
<body>
 {% block body %}  <!-- HERE -->
 <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'password_reset'%}" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{%url 'login'%}">My account</a>
              <a class="dropdown-item" href="{%url 'password_change'%}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            </div>
          </li>
        </ul>
      {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
      {% endif %}
    </div>
  </div>
</nav>
   <div class="container">
        <ol class="breadcrumb my-4">
          {% block breadcrumb %}
          {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
</html>

templates/webapp/edit_post.html
<!DOCTYPE html>
{% extends 'webapp/base.html' %}
<html>
<head>
	<title>{% block title %}Edit post{% endblock %}</title>
</head>
<body>

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards_topics' post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
  <li class="breadcrumb-item active">Edit post</li>
{% endblock %}
{% block content %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/forms.html' %}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'topic_posts' post.topic.board.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}
</body>
</html>

templates/webapp/home.html
<!DOCTYPE html>
{%extends 'webapp/base.html'%}<!--this is master page(templtae)<-->
{%load staticfiles%}
<html>
<head>

	<link rel="stylesheet" type="text/css" href="{%static 'css/web.css'%}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	
</head>
<!--This is child Template Page<-->
 <body>
    <div class="container">
      <ol class="breadcrumb my-4">
        {%block breadcrumb%}
        <li class="breadcrumb-item active ">Boards</li>
        {%endblock%}
      </ol>
      {%block content%}
      <table class="table jumbotron" >
        <thead class="thead-inverse" style="background-color: black;">
          <tr class="tbl">
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                <a href="{%url 'boards_topics' board.id %}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>

              <td class="align-middle">
                {{ board.get_posts_count }}
              </td>
              <td class="align-middle">
                {{ board.topics.count }}
              </td>
              <td>
                {% with post=board.get_last_post %}
              {% if post %}
                <small>
                  <a href="{% url 'topic_posts' board.pk post.topic.pk %}">
                    By {{ post.created_by.username }} at {{ post.create_at }}
                  </a>
                </small>
              {% else %}
                <small class="text-muted">
                  <em>No posts yet.</em>
                </small>
              {% endif %}
            {% endwith %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="container">
    <small>developed by@</small>
    <h6>Mohammad.Nazeeruddin</h6>
  </div>
    <small></small>
    {%endblock%}
  </body>

</html>

templates/webapp/new_topic.html
<!DOCTYPE html>
{%extends 'webapp/base.html'%}
{%load widget_tweaks%}

{%load staticfiles%}
<html>
<head>
	{%block title%}start a new topic {%endblock%}
	<link rel="stylesheet" type="text/css" href="{% static 'css/web.css'%}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
	{%block breadcrumb%}
	  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  	  <li class="breadcrumb-item"><a href="{% url 'boards_topics' pk=N_boards.pk %}">{{ N_boards.name }}</a></li>
      <li class="breadcrumb-item active">New topic</li>
	{%endblock%}

	{%block content%}
  	<form method="post" novalidate>
    	{% csrf_token %}
    	{% include 'includes/forms.html'%}
    	<!--including extend form here <-->
    	<button type="submit" class="btn btn-success">Post</button>
  	</form>
 	{% endblock %}


	 <!--<form method="post">
   <div class="form-group">
      <label for="id_subject">Subject</label>
      <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post</button>
  </form><-->

  <!--<form method="post" novalidate>
    {% csrf_token %}
     {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}

          {% if form.is_bound %}
        {% if field.errors %}

          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}

        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">
            {{ field.help_text }}
          </small>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Post</button>
  </form><-->
  

</body>
</html>

templates/webapp/reply_topic.html
<!DOCTYPE html>
{% extends 'webapp/base.html' %}

{% load staticfiles %}
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  
	<title>{% block title %}Post a reply{% endblock %}</title>
</head>
<body>
	{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'topic_posts' topic.board.pk topic.pk %}">{{ topic.subject }}</a></li>
  <li class="breadcrumb-item active">Post a reply</li>
{% endblock %}

{% block content %}

  <form method="post" class="mb-4" >
    {% csrf_token %}
    {% include 'includes/forms.html' %}
    
    <button type="submit" class="btn btn-success">Post a reply</button>
  </form>

  {% for post in topic.posts.all %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row mb-3">
          <div class="col-6">
            <strong class="text-muted">{{ post.created_by.username }}</strong>
          </div>
          <div class="col-6 text-right">
            <small class="text-muted">{{ post.created_at }}</small>
          </div>
        </div>
        {{ post.get_message_as_markdown  }}
      </div>
    </div>
  {% endfor %}

{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
</html>

templates/webapp/topic_posts.html
<!DOCTYPE html>
{% extends 'webapp/base.html' %}
{% load staticfiles %}


<html>
<head>
	<title>{% block title %}{{ topic.subject }}{% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
	{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}
{% block content %}

  <div class="mb-4">
    <a href="{% url 'reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
  </div>

  {% for post in topic.posts.all %}
     <div class="card mb-2 {% if forloop.first %}border-dark{% endif %}">
    <div class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
      {% if forloop.first %}
        <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
      {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
              <img src="{% static 'img/nazeer.svg' %}" alt="{{ post.created_by.username }}" class="w-100">
            <small>Posts: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at }}</small>
              </div>
            </div>
            {{ post.message }}
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'edit_post' post.topic.board.pk post.topic.pk post.pk %}"
                   class="btn btn-primary btn-sm"
                   role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  {% include 'includes/pagination.html' %}
{% endblock %}
</body>
</html>

templates/webapp/topics.html
<!DOCTYPE html>
{%extends 'webapp/base.html'%}
{%load staticfiles%}
{% load humanize %}
<html>
<head>
	<title>{%block title%} {{boards.name}}-{{block.super}} {%endblock%}</title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/web.css'%}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
 <body>
    <div class="container">
      <ol class="breadcrumb my-5">
      	{%block breadcrumb%}
        <li class="breadcrumb-item"><a href="{%url 'home'%}">Boards</a></li>
        <li class="breadcrumb-item active">{{board.name}}</li>
        {%endblock%}
      </ol>
    </div>

    {%block content%}
    <div class="mb-4">
    		<a href="{% url 'new_topics' board.pk %}" class="btn btn-primary">New topic</a>
    		<!-- This link redirecting to new_topic.html T_boards.pk matching with primary keys<-->
  	  </div>
     <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
      <!-- The related_name="topics" parameter will be used to create a reverse relationship where the Board instances will have access a list of Topic instances that belong to it.<-->
        {% url 'topic_posts' board.pk topic.pk as topic_url %}
        <tr>
          <td>
            <p class="mb-0">
              <a href="{{ topic_url }}">{{ topic.subject }}</a>
            </p>
            <small class="text-muted">
              Pages:
              {% for i in topic.get_page_range %}
                <a href="{{ topic_url }}?page={{ i }}">{{ i }}</a>
              {% endfor %}
              {% if topic.has_many_pages %}
              ... <a href="{{ topic_url }}?page={{ topic.get_page_count }}">Last Page</a>
              {% endif %}
            </small>
          </td>
          <td class="align-middle">{{ topic.starter.username }}</td>
          <td class="align-middle">{{ topic.replies }}</td>
          <td class="align-middle">{{ topic.views }}</td>
          <td class="align-middle">{{ topic.last_update|naturaltime }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
   {% include 'includes/pagination.html' %}
{%endblock%}
  </body>
}
</html>